/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_test_myffmpeg_HellowJni */

#ifndef _Included_com_example_test_test_myffmpeg_HellowJni
#define _Included_com_example_test_test_myffmpeg_HellowJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_test_myffmpeg_HellowJni
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_test_myffmpeg_HellowJni_configurationinfo
        (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_example_test_test_myffmpeg_HellowJni_getAndroidCpuType
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
