/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_test_myffmpeg_JniUtils */

#ifndef _Included_com_example_test_test_myffmpeg_JniUtils
#define _Included_com_example_test_test_myffmpeg_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_test_myffmpeg_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_test_myffmpeg_JniUtils_getStringFormC
  (JNIEnv *, jclass);
JNIEXPORT jstring JNICALLJava_com_example_test_test_myffmpeg_JniUtils_jiaMi
        (JNIEnv *env, jclass type, jstring s_);
#ifdef __cplusplus
}
#endif
#endif
